services:
  yaxt-api:
    build: .
    ports:
      - "5000:5000"
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: yaxt123
      POSTGRES_USER: yaxt
      POSTGRES_DB: Exams
    volumes:
      - ./db-config:/docker-entrypoint-initdb.d